import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Image from "next/image";
import { AuthProvider } from "@/context/auth";
import AuthButtons from "@/components/auth-buttons";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
        <nav className="bg-white text-gray-500 p-5 h-24 flex items-center justify-between">
         <Link href={'/'}><Image src={'/images/fahasa-logo.webp'} width={200} height={200} alt="logo"/></Link>
         <ul>
           <li>
            <AuthButtons/>
           </li>
         </ul>
        </nav>
        </AuthProvider>
        {children}
      </body>
    </html>
  );
}
